spring:
  profiles:
    active: local
  application:
    name: huaying
  mvc:
    throw-exception-if-no-handler-found: true # 404æ—¶æŠ›å‡ºNoHandlerFoundExceptionå¼‚å¸¸
  web:
    resources:
      add-mappings: false # å…³é—­é™æ€èµ„æºæ–‡ä»¶æ˜ å°„

huaying:
  api-base-path:
  web-site-info:
    app-id: ${spring.application.name}
    name: ğŸ§šâ€â™€ï¸ èŠ±æ¥¹
    desc: ä¸€ä¸ªåŸºäº Spring Boot æ„å»ºçš„éšæœºèµ„æº API æœåŠ¡
    url: https://api.lilu.org.cn/${spring.application.name}/
